name: Docker CI

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: make docker/build
    - run: make docker/start
    - run: make test/put
    - run: make test/get
    - run: make test/post
    - run: make docker/logs
      if: always()