name: Go CI

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.20]

    steps:
    - uses: actions/checkout@v3
    - name: Use Go ${{ matrix.node-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.node-version }}
    - run: go install
    - run: go build
    - run: go test
